import { db } from "@workspace/db";
import { categories, users } from "@workspace/db/schema";
import { eq } from "drizzle-orm";
import bcrypt from "bcrypt";

const defaultCategories = [
  { name: "Игровые аккаунты", slug: "game-accounts", icon: "🎮", sortOrder: 1 },
  { name: "Игровые предметы", slug: "game-items", icon: "⚔️", sortOrder: 2 },
  { name: "Игровая валюта", slug: "game-currency", icon: "💰", sortOrder: 3 },
  { name: "Бустинг", slug: "boosting", icon: "🚀", sortOrder: 4 },
  { name: "Услуги", slug: "services", icon: "👑", sortOrder: 5 },
  { name: "Другое", slug: "other", icon: "🛒", sortOrder: 6 },
  // Популярные игры
  { name: "World of Warcraft", slug: "wow", icon: "🐉", sortOrder: 7 },
  { name: "Counter-Strike 2", slug: "cs2", icon: "🔫", sortOrder: 8 },
  { name: "Dota 2", slug: "dota2", icon: "⚔️", sortOrder: 9 },
  { name: "League of Legends", slug: "lol", icon: "🏆", sortOrder: 10 },
  { name: "Fortnite", slug: "fortnite", icon: "🏗️", sortOrder: 11 },
  { name: "Apex Legends", slug: "apex", icon: "🐺", sortOrder: 12 },
  { name: "Valorant", slug: "valorant", icon: "🎯", sortOrder: 13 },
  { name: "Overwatch 2", slug: "overwatch2", icon: "👁️", sortOrder: 14 },
  { name: "Minecraft", slug: "minecraft", icon: "🧱", sortOrder: 15 },
  { name: "GTA V", slug: "gta5", icon: "🚗", sortOrder: 16 },
  { name: "Call of Duty", slug: "cod", icon: "💀", sortOrder: 17 },
  { name: "PUBG", slug: "pubg", icon: "🪂", sortOrder: 18 },
  { name: "Rainbow Six Siege", slug: "r6", icon: "🛡️", sortOrder: 19 },
  { name: "Rocket League", slug: "rocket-league", icon: "🚀", sortOrder: 20 },
  { name: "FIFA", slug: "fifa", icon: "⚽", sortOrder: 21 },
  { name: "NBA 2K", slug: "nba2k", icon: "🏀", sortOrder: 22 },
  { name: "The Witcher 3", slug: "witcher3", icon: "🧙", sortOrder: 23 },
  { name: "Cyberpunk 2077", slug: "cyberpunk", icon: "🤖", sortOrder: 24 },
  { name: "Elden Ring", slug: "elden-ring", icon: "👑", sortOrder: 25 },
  { name: "Baldur's Gate 3", slug: "bg3", icon: "🎲", sortOrder: 26 },
  { name: "Hogwarts Legacy", slug: "hogwarts", icon: "🧙‍♂️", sortOrder: 27 },
  { name: "Starfield", slug: "starfield", icon: "⭐", sortOrder: 28 },
  { name: "Diablo IV", slug: "diablo4", icon: "😈", sortOrder: 29 },
  { name: "Path of Exile", slug: "poe", icon: "💎", sortOrder: 30 },
  { name: "Warframe", slug: "warframe", icon: "🤖", sortOrder: 31 },
  { name: "Destiny 2", slug: "destiny2", icon: "🌟", sortOrder: 32 },
  { name: "The Division 2", slug: "division2", icon: "🦸", sortOrder: 33 },
  { name: "Borderlands 3", slug: "borderlands3", icon: "🔫", sortOrder: 34 },
  { name: "Fallout 76", slug: "fallout76", icon: "☢️", sortOrder: 35 },
  { name: "No Man's Sky", slug: "nms", icon: "🚀", sortOrder: 36 },
  { name: "Sea of Thieves", slug: "sea-of-thieves", icon: "🏴‍☠️", sortOrder: 37 },
  { name: "Among Us", slug: "among-us", icon: "🕵️", sortOrder: 38 },
  { name: "Jackbox Party Pack", slug: "jackbox", icon: "🎉", sortOrder: 39 },
  { name: "Phasmophobia", slug: "phasmophobia", icon: "👻", sortOrder: 40 },
  { name: "Dead by Daylight", slug: "dbd", icon: "🔪", sortOrder: 41 },
  { name: "Resident Evil Village", slug: "re-village", icon: "🏰", sortOrder: 42 },
  { name: "The Last of Us Part II", slug: "tlou2", icon: "🧟", sortOrder: 43 },
  { name: "God of War Ragnarök", slug: "gow-ragnarok", icon: "⚔️", sortOrder: 44 },
  { name: "Spider-Man 2", slug: "spiderman2", icon: "🕷️", sortOrder: 45 },
  { name: "Horizon Forbidden West", slug: "horizon-fw", icon: "🤖", sortOrder: 46 },
  { name: "Ratchet & Clank: Rift Apart", slug: "ratchet-clank", icon: "🛠️", sortOrder: 47 },
  { name: "Returnal", slug: "returnal", icon: "🔄", sortOrder: 48 },
  { name: "Kena: Bridge of Spirits", slug: "kena", icon: "👻", sortOrder: 49 },
  { name: "It Takes Two", slug: "it-takes-two", icon: "👫", sortOrder: 50 },
  { name: "Hades", slug: "hades", icon: "💀", sortOrder: 51 },
  { name: "Loop Hero", slug: "loop-hero", icon: "🔁", sortOrder: 52 },
  { name: "Valheim", slug: "valheim", icon: "⚔️", sortOrder: 53 },
  { name: "New World", slug: "new-world", icon: "🌍", sortOrder: 54 },
  { name: "Lost Ark", slug: "lost-ark", icon: "🏹", sortOrder: 55 },
  { name: "Albion Online", slug: "albion", icon: "⚔️", sortOrder: 56 },
  { name: "Black Desert Online", slug: "bdo", icon: "🐎", sortOrder: 57 },
  { name: "Final Fantasy XIV", slug: "ffxiv", icon: "🧙", sortOrder: 58 },
  { name: "FFXI", slug: "ffxi", icon: "🧙‍♂️", sortOrder: 59 },
  { name: "Tera", slug: "tera", icon: "🐲", sortOrder: 60 },
  { name: "Blade & Soul", slug: "blade-soul", icon: "⚔️", sortOrder: 61 },
  { name: "Aion", slug: "aion", icon: "👼", sortOrder: 62 },
  { name: "Lineage 2", slug: "l2", icon: "⚔️", sortOrder: 63 },
  { name: "World of Tanks", slug: "wot", icon: "🚗", sortOrder: 64 },
  { name: "War Thunder", slug: "war-thunder", icon: "✈️", sortOrder: 65 },
  { name: "World of Warships", slug: "wows", icon: "🚢", sortOrder: 66 },
  { name: "World of Warplanes", slug: "wowp", icon: "✈️", sortOrder: 67 },
  { name: "Armored Warfare", slug: "armored-warfare", icon: "🚗", sortOrder: 68 },
  { name: "Crossout", slug: "crossout", icon: "🔧", sortOrder: 69 },
  { name: "Enlisted", slug: "enlisted", icon: "💂", sortOrder: 70 },
  { name: "Hell Let Loose", slug: "hell-let-loose", icon: "🔥", sortOrder: 71 },
  { name: "Squad", slug: "squad", icon: "👥", sortOrder: 72 },
  { name: "Insurgency: Sandstorm", slug: "insurgency", icon: "🏜️", sortOrder: 73 },
  { name: "Battlefield 2042", slug: "bf2042", icon: "🔫", sortOrder: 74 },
  { name: "Battlefield V", slug: "bfv", icon: "🔫", sortOrder: 75 },
  { name: "Battlefield 1", slug: "bf1", icon: "🔫", sortOrder: 76 },
  { name: "Battlefield 4", slug: "bf4", icon: "🔫", sortOrder: 77 },
  { name: "Medal of Honor", slug: "moh", icon: "🎖️", sortOrder: 78 },
  { name: "Star Wars Battlefront II", slug: "swbf2", icon: "⭐", sortOrder: 79 },
  { name: "Star Wars Jedi: Fallen Order", slug: "jedi-fallen-order", icon: "⭐", sortOrder: 80 },
  { name: "Star Wars Jedi: Survivor", slug: "jedi-survivor", icon: "⭐", sortOrder: 81 },
  { name: "Mafia III", slug: "mafia3", icon: "🚗", sortOrder: 82 },
  { name: "Grand Theft Auto IV", slug: "gta4", icon: "🚗", sortOrder: 83 },
  { name: "Grand Theft Auto: San Andreas", slug: "gtasa", icon: "🚗", sortOrder: 84 },
  { name: "Grand Theft Auto III", slug: "gta3", icon: "🚗", sortOrder: 85 },
  { name: "Red Dead Redemption 2", slug: "rdr2", icon: "🐎", sortOrder: 86 },
  { name: "Red Dead Redemption", slug: "rdr", icon: "🐎", sortOrder: 87 },
  { name: "L.A. Noire", slug: "la-noire", icon: "🕵️", sortOrder: 88 },
  { name: "Max Payne 3", slug: "max-payne-3", icon: "🔫", sortOrder: 89 },
  { name: "Alan Wake", slug: "alan-wake", icon: "💡", sortOrder: 90 },
  { name: "Quantum Break", slug: "quantum-break", icon: "⏰", sortOrder: 91 },
  { name: "Control", slug: "control", icon: "🧠", sortOrder: 92 },
  { name: "Alan Wake 2", slug: "alan-wake-2", icon: "💡", sortOrder: 93 },
  { name: "Life is Strange", slug: "life-is-strange", icon: "📷", sortOrder: 94 },
  { name: "Life is Strange 2", slug: "life-is-strange-2", icon: "📷", sortOrder: 95 },
  { name: "Beyond Good & Evil", slug: "beyond-good-evil", icon: "🦸", sortOrder: 96 },
  { name: "Rayman Legends", slug: "rayman-legends", icon: "🐱", sortOrder: 97 },
  { name: "Rayman Origins", slug: "rayman-origins", icon: "🐱", sortOrder: 98 },
  { name: "Child of Light", slug: "child-of-light", icon: "✨", sortOrder: 99 },
  { name: "Transistor", slug: "transistor", icon: "🔌", sortOrder: 100 },
  { name: "Bastion", slug: "bastion", icon: "🏰", sortOrder: 101 },
  { name: "Dust: An Elysian Tail", slug: "dust", icon: "💨", sortOrder: 102 },
  { name: "Ori and the Will of the Wisps", slug: "ori-wow", icon: "🦉", sortOrder: 103 },
  { name: "Ori and the Blind Forest", slug: "ori-bf", icon: "🦉", sortOrder: 104 },
  { name: "Hollow Knight", slug: "hollow-knight", icon: "🦗", sortOrder: 105 },
  { name: "Celeste", slug: "celeste", icon: "⛰️", sortOrder: 106 },
  // Дополнительные популярные игры
  { name: "Among Us", slug: "among-us-pc", icon: "🕵️", sortOrder: 107 },
  { name: "Roblox", slug: "roblox", icon: "🎮", sortOrder: 108 },
  { name: "The Sims 4", slug: "sims4", icon: "🏠", sortOrder: 109 },
  { name: "Stardew Valley", slug: "stardew-valley", icon: "🌾", sortOrder: 110 },
  { name: "Terraria", slug: "terraria", icon: "⛏️", sortOrder: 111 },
  { name: "Undertale", slug: "undertale", icon: "💀", sortOrder: 112 },
  { name: "Hades", slug: "hades-pc", icon: "💀", sortOrder: 113 },
  { name: "Risk of Rain 2", slug: "ror2", icon: "🌧️", sortOrder: 114 },
  { name: "Monster Hunter: World", slug: "mh-world", icon: "🐉", sortOrder: 115 },
  { name: "Monster Hunter: Rise", slug: "mh-rise", icon: "🐉", sortOrder: 116 },
  { name: "Monster Hunter: Iceborne", slug: "mh-iceborne", icon: "🐉", sortOrder: 117 },
  { name: "Dark Souls 3", slug: "ds3", icon: "💀", sortOrder: 118 },
  { name: "Bloodborne", slug: "bloodborne", icon: "🩸", sortOrder: 119 },
  { name: "Sekiro: Shadows Die Twice", slug: "sekiro", icon: "⚔️", sortOrder: 120 },
  { name: "Nioh 2", slug: "nioh2", icon: "⚔️", sortOrder: 121 },
  { name: "Ghostwire: Tokyo", slug: "ghostwire-tokyo", icon: "👻", sortOrder: 122 },
  { name: "Death Stranding", slug: "death-stranding", icon: "📦", sortOrder: 123 },
  { name: "Horizon Zero Dawn", slug: "horizon-zero-dawn", icon: "🤖", sortOrder: 124 },
  { name: "A Plague Tale: Innocence", slug: "plague-tale", icon: "🐀", sortOrder: 125 },
  { name: "Assassin's Creed Valhalla", slug: "ac-valhalla", icon: "⚔️", sortOrder: 126 },
  { name: "Assassin's Creed Odyssey", slug: "ac-odyssey", icon: "⚔️", sortOrder: 127 },
  { name: "Assassin's Creed Origins", slug: "ac-origins", icon: "⚔️", sortOrder: 128 },
  { name: "Far Cry 6", slug: "farcry6", icon: "🔫", sortOrder: 129 },
  { name: "Far Cry 5", slug: "farcry5", icon: "🔫", sortOrder: 130 },
  { name: "Tom Clancy's The Division 2", slug: "division2-pc", icon: "🦸", sortOrder: 131 },
  { name: "Tom Clancy's The Division", slug: "division", icon: "🦸", sortOrder: 132 },
  { name: "Watch Dogs: Legion", slug: "watch-dogs-legion", icon: "👁️", sortOrder: 133 },
  { name: "Watch Dogs 2", slug: "watch-dogs2", icon: "👁️", sortOrder: 134 },
  { name: "Cyberpunk 2077", slug: "cyberpunk-pc", icon: "🤖", sortOrder: 135 },
  { name: "The Outer Worlds 2", slug: "outer-worlds2", icon: "🚀", sortOrder: 136 },
  { name: "The Outer Worlds", slug: "outer-worlds", icon: "🚀", sortOrder: 137 },
  { name: "Fallout: New Vegas", slug: "fallout-nv", icon: "☢️", sortOrder: 138 },
  { name: "Fallout 4", slug: "fallout4", icon: "☢️", sortOrder: 139 },
  { name: "Fallout 3", slug: "fallout3", icon: "☢️", sortOrder: 140 },
  { name: "Metro Exodus", slug: "metro-exodus", icon: "🚇", sortOrder: 141 },
  { name: "Metro: Last Light", slug: "metro-last-light", icon: "🚇", sortOrder: 142 },
  { name: "Half-Life: Alyx", slug: "hl-alyx", icon: "🥽", sortOrder: 143 },
  { name: "Portal 2", slug: "portal2", icon: "🔵", sortOrder: 144 },
  { name: "Portal", slug: "portal", icon: "🔵", sortOrder: 145 },
  { name: "Team Fortress 2", slug: "tf2", icon: "🎩", sortOrder: 146 },
  { name: "Left 4 Dead 2", slug: "l4d2", icon: "🧟", sortOrder: 147 },
  { name: "Garry's Mod", slug: "gmod", icon: "🔧", sortOrder: 148 },
  { name: "Rust", slug: "rust", icon: "🏗️", sortOrder: 149 },
  { name: "ARK: Survival Evolved", slug: "ark", icon: "🦕", sortOrder: 150 },
  { name: "7 Days to Die", slug: "7dtd", icon: "🧟", sortOrder: 151 },
  { name: "Project Zomboid", slug: "project-zomboid", icon: "🧟", sortOrder: 152 },
  { name: "DayZ", slug: "dayz", icon: "🧟", sortOrder: 153 },
  { name: "The Forest", slug: "the-forest", icon: "🌲", sortOrder: 154 },
  { name: "Green Hell", slug: "green-hell", icon: "🌴", sortOrder: 155 },
  { name: "Subnautica", slug: "subnautica", icon: "🌊", sortOrder: 156 },
  { name: "Subnautica: Below Zero", slug: "subnautica-below-zero", icon: "🧊", sortOrder: 157 },
  { name: "Barotrauma", slug: "barotrauma", icon: "🌊", sortOrder: 158 },
  { name: "Deep Rock Galactic", slug: "drg", icon: "⛏️", sortOrder: 159 },
  { name: "Lethal Company", slug: "lethal-company", icon: "👷", sortOrder: 160 },
  { name: "Phasmophobia", slug: "phasmophobia-pc", icon: "👻", sortOrder: 161 },
  { name: "DEVOUR", slug: "devour", icon: "👻", sortOrder: 162 },
  { name: "Outlast", slug: "outlast", icon: "😱", sortOrder: 163 },
  { name: "Amnesia: The Dark Descent", slug: "amnesia", icon: "😱", sortOrder: 164 },
  { name: "SOMA", slug: "soma", icon: "🧠", sortOrder: 165 },
  { name: "Prey", slug: "prey", icon: "👽", sortOrder: 166 },
  { name: "Alien: Isolation", slug: "alien-isolation", icon: "👽", sortOrder: 167 },
  { name: "Dead Space", slug: "dead-space", icon: "👽", sortOrder: 168 },
  { name: "Resident Evil 4", slug: "re4", icon: "🏰", sortOrder: 169 },
  { name: "Resident Evil 2", slug: "re2", icon: "🏰", sortOrder: 170 },
  { name: "Silent Hill 2", slug: "silent-hill-2", icon: "👻", sortOrder: 171 },
  { name: "The Evil Within 2", slug: "evil-within-2", icon: "😱", sortOrder: 172 },
  { name: "Layers of Fear", slug: "layers-of-fear", icon: "🎨", sortOrder: 173 },
  { name: "BioShock Infinite", slug: "bioshock-infinite", icon: "🏙️", sortOrder: 174 },
  { name: "BioShock", slug: "bioshock", icon: "🏙️", sortOrder: 175 },
  { name: "Mirror's Edge", slug: "mirrors-edge", icon: "🏃", sortOrder: 176 },
  { name: "Mirror's Edge Catalyst", slug: "mirrors-edge-catalyst", icon: "🏃", sortOrder: 177 },
  { name: "Dishonored 2", slug: "dishonored2", icon: "🕵️", sortOrder: 178 },
  { name: "Dishonored", slug: "dishonored", icon: "🕵️", sortOrder: 179 },
  { name: "Prey (2017)", slug: "prey-2017", icon: "👽", sortOrder: 180 },
  { name: "Deus Ex: Human Revolution", slug: "deus-ex-hr", icon: "🤖", sortOrder: 181 },
  { name: "Deus Ex: Mankind Divided", slug: "deus-ex-md", icon: "🤖", sortOrder: 182 },
  { name: "Thief", slug: "thief", icon: "🕵️", sortOrder: 183 },
  { name: "Thief (2014)", slug: "thief-2014", icon: "🕵️", sortOrder: 184 },
  { name: "Mark of the Ninja", slug: "mark-of-the-ninja", icon: "🥷", sortOrder: 185 },
  { name: "Katana Zero", slug: "katana-zero", icon: "⚔️", sortOrder: 186 },
  { name: "Hollow Knight", slug: "hollow-knight-pc", icon: "🦗", sortOrder: 187 },
  { name: "Ori and the Blind Forest", slug: "ori-blind-forest", icon: "🦉", sortOrder: 188 },
  { name: "Dead Cells", slug: "dead-cells", icon: "🗡️", sortOrder: 189 },
  { name: "Enter the Gungeon", slug: "enter-the-gungeon", icon: "🔫", sortOrder: 190 },
  { name: "Risk of Rain 2", slug: "risk-of-rain-2", icon: "🌧️", sortOrder: 191 },
  { name: "Loop Hero", slug: "loop-hero-pc", icon: "🔁", sortOrder: 192 },
  { name: "FTL: Faster Than Light", slug: "ftl", icon: "🚀", sortOrder: 193 },
  { name: "Into the Breach", slug: "into-the-breach", icon: "🤖", sortOrder: 194 },
  { name: "Slay the Spire", slug: "slay-the-spire", icon: "🃏", sortOrder: 195 },
  { name: "Hearthstone", slug: "hearthstone", icon: "🃏", sortOrder: 196 },
  { name: "Magic: The Gathering Arena", slug: "mtg-arena", icon: "🃏", sortOrder: 197 },
  { name: "Yu-Gi-Oh! Master Duel", slug: "yugioh-master-duel", icon: "🃏", sortOrder: 198 },
  { name: "Eternal Card Game", slug: "eternal", icon: "🃏", sortOrder: 199 },
  { name: "Shadowverse", slug: "shadowverse", icon: "🃏", sortOrder: 200 },
  { name: "Legends of Runeterra", slug: "lor", icon: "🃏", sortOrder: 201 },
  { name: "Teamfight Tactics", slug: "tft", icon: "🃏", sortOrder: 202 },
  { name: "Auto Chess", slug: "auto-chess", icon: "🃏", sortOrder: 203 },
  { name: "Dota Underlords", slug: "dota-underlords", icon: "🃏", sortOrder: 204 },
  { name: "Brawlhalla", slug: "brawlhalla", icon: "🥊", sortOrder: 205 },
  { name: "Smash Bros Ultimate", slug: "smash-ultimate", icon: "🥊", sortOrder: 206 },
  { name: "Multiversus", slug: "multiversus", icon: "🥊", sortOrder: 207 },
  { name: "Gang Beasts", slug: "gang-beasts", icon: "🥊", sortOrder: 208 },
  { name: "Stick Fight: The Game", slug: "stick-fight", icon: "🥊", sortOrder: 209 },
  { name: "For Honor", slug: "for-honor", icon: "⚔️", sortOrder: 210 },
  { name: "Chivalry 2", slug: "chivalry2", icon: "⚔️", sortOrder: 211 },
  { name: "Mordhau", slug: "mordhau", icon: "⚔️", sortOrder: 212 },
  { name: "Mount & Blade II: Bannerlord", slug: "mount-blade2", icon: "⚔️", sortOrder: 213 },
  { name: "Kingdom: Come Deliverance", slug: "kingdom-come", icon: "⚔️", sortOrder: 214 },
  { name: "The Banner Saga", slug: "banner-saga", icon: "⚔️", sortOrder: 215 },
  { name: "Pillars of Eternity", slug: "pillars-of-eternity", icon: "🎲", sortOrder: 216 },
  { name: "Divinity: Original Sin 2", slug: "divinity-os2", icon: "🎲", sortOrder: 217 },
  { name: "Tyranny", slug: "tyranny", icon: "🎲", sortOrder: 218 },
  { name: "Wasteland 3", slug: "wasteland3", icon: "🎲", sortOrder: 219 },
  { name: "Disco Elysium", slug: "disco-elysium", icon: "🕵️", sortOrder: 220 },
  { name: "Planescape: Torment", slug: "planescape-torment", icon: "🎲", sortOrder: 221 },
  { name: "Baldur's Gate II", slug: "bg2", icon: "🎲", sortOrder: 222 },
  { name: "Icewind Dale", slug: "icewind-dale", icon: "🎲", sortOrder: 223 },
  { name: "Neverwinter Nights", slug: "neverwinter-nights", icon: "🎲", sortOrder: 224 },
  { name: "Dragon Age: Inquisition", slug: "dragon-age-inquisition", icon: "🐉", sortOrder: 225 },
  { name: "Dragon Age: Origins", slug: "dragon-age-origins", icon: "🐉", sortOrder: 226 },
  { name: "Mass Effect 2", slug: "mass-effect-2", icon: "🚀", sortOrder: 227 },
  { name: "Mass Effect 3", slug: "mass-effect-3", icon: "🚀", sortOrder: 228 },
  { name: "Mass Effect: Andromeda", slug: "mass-effect-andromeda", icon: "🚀", sortOrder: 229 },
  { name: "Jade Cocoon", slug: "jade-cocoon", icon: "🦋", sortOrder: 230 },
  { name: "Chrono Trigger", slug: "chrono-trigger", icon: "⏰", sortOrder: 231 },
  { name: "EarthBound", slug: "earthbound", icon: "🌍", sortOrder: 232 },
  { name: "Secret of Mana", slug: "secret-of-mana", icon: "⚔️", sortOrder: 233 },
  { name: "Lunar: Silver Star Story", slug: "lunar-silver-star", icon: "🌙", sortOrder: 234 },
  { name: "Grandia", slug: "grandia", icon: "🌍", sortOrder: 235 },
  { name: "Breath of Fire", slug: "breath-of-fire", icon: "🐉", sortOrder: 236 },
  { name: "Secret of Evermore", slug: "secret-of-evermore", icon: "⚔️", sortOrder: 237 },
  { name: "Illusion of Gaia", slug: "illusion-of-gaia", icon: "🌍", sortOrder: 238 },
  { name: "Lufia II: Rise of the Sinistrals", slug: "lufia2", icon: "⚔️", sortOrder: 239 },
  { name: "Live A Live", slug: "live-a-live", icon: "⏰", sortOrder: 240 },
  { name: "Secret of Mana 2", slug: "secret-of-mana-2", icon: "⚔️", sortOrder: 241 },
  { name: "Grandia 2", slug: "grandia2", icon: "🌍", sortOrder: 242 },
  { name: "Breath of Fire II", slug: "breath-of-fire-2", icon: "🐉", sortOrder: 243 },
  { name: "EarthBound Beginnings", slug: "earthbound-beginnings", icon: "🌍", sortOrder: 244 },
  { name: "Chrono Cross", slug: "chrono-cross", icon: "⏰", sortOrder: 245 },
  { name: "Vagrant Story", slug: "vagrant-story", icon: "⚔️", sortOrder: 246 },
  { name: "Final Fantasy VI", slug: "ff6", icon: "🧙", sortOrder: 247 },
  { name: "Final Fantasy VII", slug: "ff7", icon: "🧙", sortOrder: 248 },
  { name: "Final Fantasy VIII", slug: "ff8", icon: "🧙", sortOrder: 249 },
  { name: "Final Fantasy IX", slug: "ff9", icon: "🧙", sortOrder: 250 },
  { name: "Final Fantasy X", slug: "ff10", icon: "🧙", sortOrder: 251 },
  { name: "Final Fantasy X-2", slug: "ff10-2", icon: "🧙", sortOrder: 252 },
  { name: "Final Fantasy XII", slug: "ff12", icon: "🧙", sortOrder: 253 },
  { name: "Final Fantasy XIII", slug: "ff13", icon: "🧙", sortOrder: 254 },
  { name: "Final Fantasy XIII-2", slug: "ff13-2", icon: "🧙", sortOrder: 255 },
  { name: "Lightning Returns", slug: "lightning-returns", icon: "🧙", sortOrder: 256 },
  { name: "Final Fantasy XV", slug: "ff15", icon: "🧙", sortOrder: 257 },
  { name: "Kingdom Hearts", slug: "kingdom-hearts", icon: "🗝️", sortOrder: 258 },
  { name: "Kingdom Hearts II", slug: "kingdom-hearts-2", icon: "🗝️", sortOrder: 259 },
  { name: "Kingdom Hearts III", slug: "kingdom-hearts-3", icon: "🗝️", sortOrder: 260 },
  { name: "Persona 3 Portable", slug: "persona3p", icon: "👤", sortOrder: 261 },
  { name: "Persona 4 Golden", slug: "persona4g", icon: "👤", sortOrder: 262 },
  { name: "Persona 5 Royal", slug: "persona5r", icon: "👤", sortOrder: 263 },
  { name: "Persona 5 Strikers", slug: "persona5-strikers", icon: "👤", sortOrder: 264 },
  { name: "Shin Megami Tensei III", slug: "smt3", icon: "👹", sortOrder: 265 },
  { name: "Shin Megami Tensei IV", slug: "smt4", icon: "👹", sortOrder: 266 },
  { name: "Shin Megami Tensei V", slug: "smt5", icon: "👹", sortOrder: 267 },
  { name: "Digital Devil Saga", slug: "dds", icon: "👹", sortOrder: 268 },
  { name: "Devil Survivor 2", slug: "devil-survivor-2", icon: "👹", sortOrder: 269 },
  { name: "Soul Hackers 2", slug: "soul-hackers-2", icon: "👹", sortOrder: 270 },
  { name: "Catherine", slug: "catherine", icon: "🗼", sortOrder: 271 },
  { name: "Catherine: Full Body", slug: "catherine-full-body", icon: "🗼", sortOrder: 272 },
  { name: "Nocturne", slug: "nocturne", icon: "🌙", sortOrder: 273 },
  { name: "Radiant Historia", slug: "radiant-historia", icon: "📖", sortOrder: 274 },
  { name: "Child of Light", slug: "child-of-light-pc", icon: "✨", sortOrder: 275 },
  { name: "Transistor", slug: "transistor-pc", icon: "🔌", sortOrder: 276 },
  { name: "Bastion", slug: "bastion-pc", icon: "🏰", sortOrder: 277 },
  { name: "Fez", slug: "fez-pc", icon: "🎩", sortOrder: 278 },
  { name: "Braid", slug: "braid-pc", icon: "💇", sortOrder: 279 },
  { name: "The Witness", slug: "the-witness-pc", icon: "👁️", sortOrder: 280 },
  { name: "Monument Valley", slug: "monument-valley-pc", icon: "🏔️", sortOrder: 281 },
  { name: "Monument Valley 2", slug: "monument-valley-2-pc", icon: "🏔️", sortOrder: 282 },
  { name: "The Room", slug: "the-room-pc", icon: "🚪", sortOrder: 283 },
  { name: "The Room Two", slug: "the-room-two-pc", icon: "🚪", sortOrder: 284 },
  { name: "The Room Three", slug: "the-room-three-pc", icon: "🚪", sortOrder: 285 },
  { name: "The Room Four", slug: "the-room-four", icon: "🚪", sortOrder: 286 },
  { name: "Cube Escape", slug: "cube-escape", icon: "🧊", sortOrder: 287 },
  { name: "LSD: Dream Emulator", slug: "lsd-dream-emulator-pc", icon: "🌈", sortOrder: 288 },
  { name: "Superliminal", slug: "superliminal", icon: "🧠", sortOrder: 289 },
  { name: "Portal Stories: Mel", slug: "portal-stories-mel", icon: "🔵", sortOrder: 290 },
  { name: "Thinking with Time Machine", slug: "thinking-with-time-machine", icon: "⏰", sortOrder: 291 },
  { name: "The Stanley Parable", slug: "stanley-parable", icon: "🚪", sortOrder: 292 },
  { name: "Gone Home", slug: "gone-home", icon: "🏠", sortOrder: 293 },
  { name: "What Remains of Edith Finch", slug: "edith-finch", icon: "🐦", sortOrder: 294 },
  { name: "Firewatch", slug: "firewatch", icon: "🏞️", sortOrder: 295 },
  { name: "A Short Hike", slug: "short-hike", icon: "🥾", sortOrder: 296 },
  { name: "Journey", slug: "journey", icon: "🏜️", sortOrder: 297 },
  { name: "Flower", slug: "flower", icon: "🌸", sortOrder: 298 },
  { name: "Abzû", slug: "abzu", icon: "🐠", sortOrder: 299 },
  { name: "Cloud Chamber", slug: "cloud-chamber", icon: "☁️", sortOrder: 300 },
  { name: "Eastshade", slug: "eastshade", icon: "🎨", sortOrder: 301 },
  { name: "Gris", slug: "gris", icon: "🎨", sortOrder: 302 },
  { name: "Spiritfarer", slug: "spiritfarer", icon: "⛵", sortOrder: 303 },
  { name: "Hades", slug: "hades-game", icon: "💀", sortOrder: 304 },
  { name: "Loop Hero", slug: "loop-hero-game", icon: "🔁", sortOrder: 305 },
  { name: "Valheim", slug: "valheim-game", icon: "⚔️", sortOrder: 306 },
  { name: "PUBG Mobile", slug: "pubg-mobile", icon: "📱", sortOrder: 107 },
  { name: "Free Fire", slug: "free-fire", icon: "📱", sortOrder: 108 },
  { name: "Mobile Legends", slug: "mobile-legends", icon: "📱", sortOrder: 109 },
  { name: "Arena of Valor", slug: "arena-of-valor", icon: "📱", sortOrder: 110 },
  { name: "Clash of Clans", slug: "clash-of-clans", icon: "🏰", sortOrder: 111 },
  { name: "Clash Royale", slug: "clash-royale", icon: "⚔️", sortOrder: 112 },
  { name: "Brawl Stars", slug: "brawl-stars", icon: "⭐", sortOrder: 113 },
  { name: "Among Us Mobile", slug: "among-us-mobile", icon: "🕵️", sortOrder: 114 },
  { name: "Genshin Impact", slug: "genshin-impact", icon: "🌪️", sortOrder: 115 },
  { name: "Honkai: Star Rail", slug: "honkai-star-rail", icon: "🚂", sortOrder: 116 },
  { name: "Honkai Impact 3rd", slug: "honkai-impact", icon: "⚡", sortOrder: 117 },
  { name: "Zenless Zone Zero", slug: "zenless-zone-zero", icon: "🚫", sortOrder: 118 },
  { name: "Wuthering Waves", slug: "wuthering-waves", icon: "🌊", sortOrder: 119 },
  { name: "Tower of Fantasy", slug: "tower-of-fantasy", icon: "🏰", sortOrder: 120 },
  { name: "Punishing: Gray Raven", slug: "punishing-gray-raven", icon: "🐦", sortOrder: 121 },
  { name: "Reverse: 1999", slug: "reverse-1999", icon: "🔄", sortOrder: 122 },
  { name: "Arknights", slug: "arknights", icon: "🏥", sortOrder: 123 },
  { name: "Blue Archive", slug: "blue-archive", icon: "📚", sortOrder: 124 },
  { name: "Azur Lane", slug: "azur-lane", icon: "🚢", sortOrder: 125 },
  { name: "Fate/Grand Order", slug: "fgo", icon: "⚔️", sortOrder: 126 },
  { name: "Princess Connect! Re:Dive", slug: "pcr", icon: "👸", sortOrder: 127 },
  { name: "Uma Musume Pretty Derby", slug: "uma-musume", icon: "🐎", sortOrder: 128 },
  { name: "Love Live! School Idol Festival", slug: "love-live", icon: "🎤", sortOrder: 129 },
  { name: "BanG Dream! Girls Band Party!", slug: "bang-dream", icon: "🎸", sortOrder: 130 },
  { name: "Project Sekai", slug: "project-sekai", icon: "🎵", sortOrder: 131 },
  { name: "D4DJ Groovy Mix", slug: "d4dj", icon: "🎧", sortOrder: 132 },
  { name: "Ensemble Stars!!", slug: "ensemble-stars", icon: "⭐", sortOrder: 133 },
  { name: "A3!", slug: "a3", icon: "🎭", sortOrder: 134 },
  { name: "Onmyoji", slug: "onmyoji", icon: "👹", sortOrder: 135 },
  { name: "Food Fantasy", slug: "food-fantasy", icon: "🍽️", sortOrder: 136 },
  { name: "AFK Arena", slug: "afk-arena", icon: "⚔️", sortOrder: 137 },
  { name: "Summoners War", slug: "summoners-war", icon: "🔮", sortOrder: 138 },
  { name: "Raid: Shadow Legends", slug: "raid-shadow-legends", icon: "👑", sortOrder: 139 },
  { name: "Rise of Kingdoms", slug: "rise-of-kingdoms", icon: "🏰", sortOrder: 140 },
  { name: "Lords Mobile", slug: "lords-mobile", icon: "👑", sortOrder: 141 },
  { name: "Game of Moans", slug: "game-of-moans", icon: "🏰", sortOrder: 142 },
  { name: "Boom Beach", slug: "boom-beach", icon: "🏖️", sortOrder: 143 },
  { name: "Hay Day", slug: "hay-day", icon: "🌾", sortOrder: 144 },
  { name: "Farm Heroes Saga", slug: "farm-heroes-saga", icon: "🌾", sortOrder: 145 },
  { name: "Candy Crush Saga", slug: "candy-crush", icon: "🍬", sortOrder: 146 },
  { name: "Angry Birds", slug: "angry-birds", icon: "🐦", sortOrder: 147 },
  { name: "Fruit Ninja", slug: "fruit-ninja", icon: "🍎", sortOrder: 148 },
  { name: "Temple Run", slug: "temple-run", icon: "🏃", sortOrder: 149 },
  { name: "Subway Surfers", slug: "subway-surfers", icon: "🚇", sortOrder: 150 },
  { name: "Hill Climb Racing", slug: "hill-climb-racing", icon: "🏔️", sortOrder: 151 },
  { name: "Asphalt 9", slug: "asphalt-9", icon: "🏎️", sortOrder: 152 },
  { name: "Real Racing 3", slug: "real-racing-3", icon: "🏎️", sortOrder: 153 },
  { name: "Need for Speed: No Limits", slug: "nfs-no-limits", icon: "🏎️", sortOrder: 154 },
  { name: "CSR Racing 2", slug: "csr-racing-2", icon: "🏎️", sortOrder: 155 },
  { name: "Mario Kart Tour", slug: "mario-kart-tour", icon: "🏎️", sortOrder: 156 },
  { name: "Pokémon GO", slug: "pokemon-go", icon: "🐾", sortOrder: 157 },
  { name: "Harry Potter: Wizards Unite", slug: "hp-wizards-unite", icon: "🧙", sortOrder: 158 },
  { name: "Ingress", slug: "ingress", icon: "👽", sortOrder: 159 },
  { name: "The Walking Dead: No Man's Land", slug: "twd-no-mans-land", icon: "🧟", sortOrder: 160 },
  { name: "The Walking Dead: Our World", slug: "twd-our-world", icon: "🧟", sortOrder: 161 },
  { name: "State of Survival", slug: "state-of-survival", icon: "🧟", sortOrder: 162 },
  { name: "Last Shelter: Survival", slug: "last-shelter", icon: "Smartphone", sortOrder: 163 },
  { name: "Puzzles & Survival", slug: "puzzles-survival", icon: "🧩", sortOrder: 164 },
  { name: "Bloons TD 6", slug: "bloons-td6", icon: "🎈", sortOrder: 165 },
  { name: "Plants vs Zombies", slug: "pvz", icon: "🌱", sortOrder: 166 },
  { name: "Plants vs Zombies 2", slug: "pvz2", icon: "🌱", sortOrder: 167 },
  { name: "Kingdom: New Lands", slug: "kingdom-new-lands", icon: "🏰", sortOrder: 168 },
  { name: "Kingdom: Two Crowns", slug: "kingdom-two-crowns", icon: "👑", sortOrder: 169 },
  { name: "Mini Metro", slug: "mini-metro", icon: "🚇", sortOrder: 170 },
  { name: "Ticket to Ride", slug: "ticket-to-ride", icon: "🎫", sortOrder: 171 },
  { name: "Monopoly", slug: "monopoly", icon: "💰", sortOrder: 172 },
  { name: "Scrabble", slug: "scrabble", icon: "🔤", sortOrder: 173 },
  { name: "Words with Friends", slug: "words-with-friends", icon: "🔤", sortOrder: 174 },
  { name: "Rummikub", slug: "rummikub", icon: "🀫", sortOrder: 175 },
  { name: "Uno", slug: "uno", icon: "🃏", sortOrder: 176 },
  { name: "Phase 10", slug: "phase-10", icon: "🔢", sortOrder: 177 },
  { name: "Spaceteam", slug: "spaceteam", icon: "🚀", sortOrder: 178 },
  { name: "The Game of Life", slug: "game-of-life", icon: "👨‍👩‍👧‍👦", sortOrder: 179 },
  { name: "The Oregon Trail", slug: "oregon-trail", icon: "🐂", sortOrder: 180 },
  { name: "Civilization VI", slug: "civ6", icon: "🏛️", sortOrder: 181 },
  { name: "Frostpunk: Beyond the Ice", slug: "frostpunk-mobile", icon: "🧊", sortOrder: 182 },
  { name: "This War of Mine", slug: "this-war-of-mine", icon: "🏚️", sortOrder: 183 },
  { name: "Papers, Please", slug: "papers-please", icon: "📄", sortOrder: 184 },
  { name: "Reigns", slug: "reigns", icon: "👑", sortOrder: 185 },
  { name: "Kingdom: New Lands", slug: "kingdom-mobile", icon: "🏰", sortOrder: 186 },
  { name: "FTL: Faster Than Light", slug: "ftl", icon: "🚀", sortOrder: 187 },
  { name: "Stardew Valley", slug: "stardew-valley", icon: "🌾", sortOrder: 188 },
  { name: "Don't Starve: Pocket Edition", slug: "dont-starve-pocket", icon: "🌲", sortOrder: 189 },
  { name: "Mini Metro", slug: "mini-metro-mobile", icon: "🚇", sortOrder: 190 },
  { name: "Ticket to Ride", slug: "ticket-to-ride-mobile", icon: "🎫", sortOrder: 191 },
  { name: "Carcassonne", slug: "carcassonne", icon: "🏰", sortOrder: 192 },
  { name: "Catan", slug: "catan", icon: "🏝️", sortOrder: 193 },
  { name: "Wingspan", slug: "wingspan", icon: "🦅", sortOrder: 194 },
  { name: "Azul", slug: "azul", icon: "🔵", sortOrder: 195 },
  { name: "Splendor", slug: "splendor", icon: "💎", sortOrder: 196 },
  { name: "Ticket to Ride: First Journey", slug: "ticket-to-ride-first", icon: "🎫", sortOrder: 197 },
  { name: "The Room", slug: "the-room", icon: "🚪", sortOrder: 198 },
  { name: "The Room Two", slug: "the-room-two", icon: "🚪", sortOrder: 199 },
  { name: "The Room Three", slug: "the-room-three", icon: "🚪", sortOrder: 200 },
  { name: "Monument Valley", slug: "monument-valley", icon: "🏔️", sortOrder: 201 },
  { name: "Monument Valley 2", slug: "monument-valley-2", icon: "🏔️", sortOrder: 202 },
  // Дополнительные мобильные игры
  { name: "Roblox Mobile", slug: "roblox-mobile", icon: "🎮", sortOrder: 203 },
  { name: "Minecraft: Pocket Edition", slug: "minecraft-pe", icon: "🧱", sortOrder: 204 },
  { name: "Terraria Mobile", slug: "terraria-mobile", icon: "⛏️", sortOrder: 205 },
  { name: "Undertale Mobile", slug: "undertale-mobile", icon: "💀", sortOrder: 206 },
  { name: "Hollow Knight Mobile", slug: "hollow-knight-mobile", icon: "🦗", sortOrder: 207 },
  { name: "Dead Cells Mobile", slug: "dead-cells-mobile", icon: "🗡️", sortOrder: 208 },
  { name: "Risk of Rain 2 Mobile", slug: "ror2-mobile", icon: "🌧️", sortOrder: 209 },
  { name: "FTL Mobile", slug: "ftl-mobile", icon: "🚀", sortOrder: 210 },
  { name: "Into the Breach Mobile", slug: "into-the-breach-mobile", icon: "🤖", sortOrder: 211 },
  { name: "Slay the Spire Mobile", slug: "slay-the-spire-mobile", icon: "🃏", sortOrder: 212 },
  { name: "Hearthstone Mobile", slug: "hearthstone-mobile", icon: "🃏", sortOrder: 213 },
  { name: "Magic: The Gathering Arena Mobile", slug: "mtg-arena-mobile", icon: "🃏", sortOrder: 214 },
  { name: "Yu-Gi-Oh! Master Duel Mobile", slug: "yugioh-master-duel-mobile", icon: "🃏", sortOrder: 215 },
  { name: "Shadowverse Mobile", slug: "shadowverse-mobile", icon: "🃏", sortOrder: 216 },
  { name: "Legends of Runeterra Mobile", slug: "lor-mobile", icon: "🃏", sortOrder: 217 },
  { name: "Teamfight Tactics Mobile", slug: "tft-mobile", icon: "🃏", sortOrder: 218 },
  { name: "Auto Chess Mobile", slug: "auto-chess-mobile", icon: "🃏", sortOrder: 219 },
  { name: "Dota Underlords Mobile", slug: "dota-underlords-mobile", icon: "🃏", sortOrder: 220 },
  { name: "Brawlhalla Mobile", slug: "brawlhalla-mobile", icon: "🥊", sortOrder: 221 },
  { name: "Smash Bros Ultimate Mobile", slug: "smash-ultimate-mobile", icon: "🥊", sortOrder: 222 },
  { name: "Multiversus Mobile", slug: "multiversus-mobile", icon: "🥊", sortOrder: 223 },
  { name: "Gang Beasts Mobile", slug: "gang-beasts-mobile", icon: "🥊", sortOrder: 224 },
  { name: "Stick Fight Mobile", slug: "stick-fight-mobile", icon: "🥊", sortOrder: 225 },
  { name: "For Honor Mobile", slug: "for-honor-mobile", icon: "⚔️", sortOrder: 226 },
  { name: "Chivalry 2 Mobile", slug: "chivalry2-mobile", icon: "⚔️", sortOrder: 227 },
  { name: "Mordhau Mobile", slug: "mordhau-mobile", icon: "⚔️", sortOrder: 228 },
  { name: "Mount & Blade II Mobile", slug: "mount-blade2-mobile", icon: "⚔️", sortOrder: 229 },
  { name: "Kingdom: Come Deliverance Mobile", slug: "kingdom-come-mobile", icon: "⚔️", sortOrder: 230 },
  { name: "The Banner Saga Mobile", slug: "banner-saga-mobile", icon: "⚔️", sortOrder: 231 },
  { name: "Pillars of Eternity Mobile", slug: "pillars-of-eternity-mobile", icon: "🎲", sortOrder: 232 },
  { name: "Divinity: Original Sin 2 Mobile", slug: "divinity-os2-mobile", icon: "🎲", sortOrder: 233 },
  { name: "Tyranny Mobile", slug: "tyranny-mobile", icon: "🎲", sortOrder: 234 },
  { name: "Wasteland 3 Mobile", slug: "wasteland3-mobile", icon: "🎲", sortOrder: 235 },
  { name: "Disco Elysium Mobile", slug: "disco-elysium-mobile", icon: "🕵️", sortOrder: 236 },
  { name: "Planescape: Torment Mobile", slug: "planescape-torment-mobile", icon: "🎲", sortOrder: 237 },
  { name: "Baldur's Gate II Mobile", slug: "bg2-mobile", icon: "🎲", sortOrder: 238 },
  { name: "Icewind Dale Mobile", slug: "icewind-dale-mobile", icon: "🎲", sortOrder: 239 },
  { name: "Neverwinter Nights Mobile", slug: "neverwinter-nights-mobile", icon: "🎲", sortOrder: 240 },
  { name: "Dragon Age: Inquisition Mobile", slug: "dragon-age-inquisition-mobile", icon: "🐉", sortOrder: 241 },
  { name: "Dragon Age: Origins Mobile", slug: "dragon-age-origins-mobile", icon: "🐉", sortOrder: 242 },
  { name: "Mass Effect 2 Mobile", slug: "mass-effect-2-mobile", icon: "🚀", sortOrder: 243 },
  { name: "Mass Effect 3 Mobile", slug: "mass-effect-3-mobile", icon: "🚀", sortOrder: 244 },
  { name: "Mass Effect: Andromeda Mobile", slug: "mass-effect-andromeda-mobile", icon: "🚀", sortOrder: 245 },
  { name: "Jade Cocoon Mobile", slug: "jade-cocoon-mobile", icon: "🦋", sortOrder: 246 },
  { name: "Chrono Trigger Mobile", slug: "chrono-trigger-mobile", icon: "⏰", sortOrder: 247 },
  { name: "EarthBound Mobile", slug: "earthbound-mobile", icon: "🌍", sortOrder: 248 },
  { name: "Secret of Mana Mobile", slug: "secret-of-mana-mobile", icon: "⚔️", sortOrder: 249 },
  { name: "Lunar: Silver Star Story Mobile", slug: "lunar-silver-star-mobile", icon: "🌙", sortOrder: 250 },
  { name: "Grandia Mobile", slug: "grandia-mobile", icon: "🌍", sortOrder: 251 },
  { name: "Breath of Fire Mobile", slug: "breath-of-fire-mobile", icon: "🐉", sortOrder: 252 },
  { name: "Secret of Evermore Mobile", slug: "secret-of-evermore-mobile", icon: "⚔️", sortOrder: 253 },
  { name: "Illusion of Gaia Mobile", slug: "illusion-of-gaia-mobile", icon: "🌍", sortOrder: 254 },
  { name: "Lufia II Mobile", slug: "lufia2-mobile", icon: "⚔️", sortOrder: 255 },
  { name: "Live A Live Mobile", slug: "live-a-live-mobile", icon: "⏰", sortOrder: 256 },
  { name: "Secret of Mana 2 Mobile", slug: "secret-of-mana-2-mobile", icon: "⚔️", sortOrder: 257 },
  { name: "Grandia 2 Mobile", slug: "grandia2-mobile", icon: "🌍", sortOrder: 258 },
  { name: "Breath of Fire II Mobile", slug: "breath-of-fire-2-mobile", icon: "🐉", sortOrder: 259 },
  { name: "EarthBound Beginnings Mobile", slug: "earthbound-beginnings-mobile", icon: "🌍", sortOrder: 260 },
  { name: "Chrono Cross Mobile", slug: "chrono-cross-mobile", icon: "⏰", sortOrder: 261 },
  { name: "Vagrant Story Mobile", slug: "vagrant-story-mobile", icon: "⚔️", sortOrder: 262 },
  { name: "Final Fantasy VI Mobile", slug: "ff6-mobile", icon: "🧙", sortOrder: 263 },
  { name: "Final Fantasy VII Mobile", slug: "ff7-mobile", icon: "🧙", sortOrder: 264 },
  { name: "Final Fantasy VIII Mobile", slug: "ff8-mobile", icon: "🧙", sortOrder: 265 },
  { name: "Final Fantasy IX Mobile", slug: "ff9-mobile", icon: "🧙", sortOrder: 266 },
  { name: "Final Fantasy X Mobile", slug: "ff10-mobile", icon: "🧙", sortOrder: 267 },
  { name: "Final Fantasy X-2 Mobile", slug: "ff10-2-mobile", icon: "🧙", sortOrder: 268 },
  { name: "Final Fantasy XII Mobile", slug: "ff12-mobile", icon: "🧙", sortOrder: 269 },
  { name: "Final Fantasy XIII Mobile", slug: "ff13-mobile", icon: "🧙", sortOrder: 270 },
  { name: "Final Fantasy XIII-2 Mobile", slug: "ff13-2-mobile", icon: "🧙", sortOrder: 271 },
  { name: "Lightning Returns Mobile", slug: "lightning-returns-mobile", icon: "🧙", sortOrder: 272 },
  { name: "Final Fantasy XV Mobile", slug: "ff15-mobile", icon: "🧙", sortOrder: 273 },
  { name: "Kingdom Hearts Mobile", slug: "kingdom-hearts-mobile", icon: "🗝️", sortOrder: 274 },
  { name: "Kingdom Hearts II Mobile", slug: "kingdom-hearts-2-mobile", icon: "🗝️", sortOrder: 275 },
  { name: "Kingdom Hearts III Mobile", slug: "kingdom-hearts-3-mobile", icon: "🗝️", sortOrder: 276 },
  { name: "Persona 3 Portable Mobile", slug: "persona3p-mobile", icon: "👤", sortOrder: 277 },
  { name: "Persona 4 Golden Mobile", slug: "persona4g-mobile", icon: "👤", sortOrder: 278 },
  { name: "Persona 5 Royal Mobile", slug: "persona5r-mobile", icon: "👤", sortOrder: 279 },
  { name: "Persona 5 Strikers Mobile", slug: "persona5-strikers-mobile", icon: "👤", sortOrder: 280 },
  { name: "Shin Megami Tensei III Mobile", slug: "smt3-mobile", icon: "👹", sortOrder: 281 },
  { name: "Shin Megami Tensei IV Mobile", slug: "smt4-mobile", icon: "👹", sortOrder: 282 },
  { name: "Shin Megami Tensei V Mobile", slug: "smt5-mobile", icon: "👹", sortOrder: 283 },
  { name: "Digital Devil Saga Mobile", slug: "dds-mobile", icon: "👹", sortOrder: 284 },
  { name: "Devil Survivor 2 Mobile", slug: "devil-survivor-2-mobile", icon: "👹", sortOrder: 285 },
  { name: "Soul Hackers 2 Mobile", slug: "soul-hackers-2-mobile", icon: "👹", sortOrder: 286 },
  { name: "Catherine Mobile", slug: "catherine-mobile", icon: "🗼", sortOrder: 287 },
  { name: "Catherine: Full Body Mobile", slug: "catherine-full-body-mobile", icon: "🗼", sortOrder: 288 },
  { name: "Nocturne Mobile", slug: "nocturne-mobile", icon: "🌙", sortOrder: 289 },
  { name: "Radiant Historia Mobile", slug: "radiant-historia-mobile", icon: "📖", sortOrder: 290 },
  { name: "Child of Light Mobile", slug: "child-of-light-mobile", icon: "✨", sortOrder: 291 },
  { name: "Transistor Mobile", slug: "transistor-mobile", icon: "🔌", sortOrder: 292 },
  { name: "Bastion Mobile", slug: "bastion-mobile", icon: "🏰", sortOrder: 293 },
  { name: "Fez Mobile", slug: "fez-mobile", icon: "🎩", sortOrder: 294 },
  { name: "Braid Mobile", slug: "braid-mobile", icon: "💇", sortOrder: 295 },
  { name: "The Witness Mobile", slug: "the-witness-mobile", icon: "👁️", sortOrder: 296 },
  { name: "Superliminal Mobile", slug: "superliminal-mobile", icon: "🧠", sortOrder: 297 },
  { name: "Portal Stories: Mel Mobile", slug: "portal-stories-mel-mobile", icon: "🔵", sortOrder: 298 },
  { name: "Thinking with Time Machine Mobile", slug: "thinking-with-time-machine-mobile", icon: "⏰", sortOrder: 299 },
  { name: "The Stanley Parable Mobile", slug: "stanley-parable-mobile", icon: "🚪", sortOrder: 300 },
  { name: "Gone Home Mobile", slug: "gone-home-mobile", icon: "🏠", sortOrder: 301 },
  { name: "What Remains of Edith Finch Mobile", slug: "edith-finch-mobile", icon: "🐦", sortOrder: 302 },
  { name: "Firewatch Mobile", slug: "firewatch-mobile", icon: "🏞️", sortOrder: 303 },
  { name: "A Short Hike Mobile", slug: "short-hike-mobile", icon: "🥾", sortOrder: 304 },
  { name: "Journey Mobile", slug: "journey-mobile", icon: "🏜️", sortOrder: 305 },
  { name: "Flower Mobile", slug: "flower-mobile", icon: "🌸", sortOrder: 306 },
  { name: "Abzû Mobile", slug: "abzu-mobile", icon: "🐠", sortOrder: 307 },
  { name: "Cloud Chamber Mobile", slug: "cloud-chamber-mobile", icon: "☁️", sortOrder: 308 },
  { name: "Eastshade Mobile", slug: "eastshade-mobile", icon: "🎨", sortOrder: 309 },
  { name: "Gris Mobile", slug: "gris-mobile", icon: "🎨", sortOrder: 310 },
  { name: "Spiritfarer Mobile", slug: "spiritfarer-mobile", icon: "⛵", sortOrder: 311 },
  { name: "The Witness", slug: "the-witness", icon: "👁️", sortOrder: 203 },
  { name: "LSD: Dream Emulator", slug: "lsd-dream-emulator", icon: "🌈", sortOrder: 204 },
  { name: "Fez", slug: "fez", icon: "🎩", sortOrder: 205 },
  { name: "Braid", slug: "braid", icon: "💇", sortOrder: 206 },
  // Приложения
  { name: "Telegram", slug: "telegram", icon: "💬", sortOrder: 207 },
  { name: "Discord", slug: "discord", icon: "🎮", sortOrder: 208 },
  { name: "WhatsApp", slug: "whatsapp", icon: "💬", sortOrder: 209 },
  { name: "Signal", slug: "signal", icon: "🔒", sortOrder: 210 },
  { name: "Slack", slug: "slack", icon: "💼", sortOrder: 211 },
  { name: "Microsoft Teams", slug: "teams", icon: "👥", sortOrder: 212 },
  { name: "Zoom", slug: "zoom", icon: "📹", sortOrder: 213 },
  { name: "Skype", slug: "skype", icon: "📹", sortOrder: 214 },
  { name: "Google Meet", slug: "google-meet", icon: "📹", sortOrder: 215 },
  { name: "FaceTime", slug: "facetime", icon: "📹", sortOrder: 216 },
  { name: "Instagram", slug: "instagram", icon: "📷", sortOrder: 217 },
  { name: "Facebook", slug: "facebook", icon: "👥", sortOrder: 218 },
  { name: "Twitter", slug: "twitter", icon: "🐦", sortOrder: 219 },
  { name: "TikTok", slug: "tiktok", icon: "🎵", sortOrder: 220 },
  { name: "YouTube", slug: "youtube", icon: "▶️", sortOrder: 221 },
  { name: "Twitch", slug: "twitch", icon: "▶️", sortOrder: 222 },
  { name: "Spotify", slug: "spotify", icon: "🎵", sortOrder: 223 },
  { name: "Apple Music", slug: "apple-music", icon: "🎵", sortOrder: 224 },
  { name: "SoundCloud", slug: "soundcloud", icon: "🎵", sortOrder: 225 },
  { name: "Deezer", slug: "deezer", icon: "🎵", sortOrder: 226 },
  { name: "Netflix", slug: "netflix", icon: "🎬", sortOrder: 227 },
  { name: "HBO Max", slug: "hbo-max", icon: "🎬", sortOrder: 228 },
  { name: "Disney+", slug: "disney-plus", icon: "🎬", sortOrder: 229 },
  { name: "Amazon Prime Video", slug: "amazon-prime", icon: "🎬", sortOrder: 230 },
  { name: "Hulu", slug: "hulu", icon: "🎬", sortOrder: 231 },
  { name: "Crunchyroll", slug: "crunchyroll", icon: "🎬", sortOrder: 232 },
  { name: "Funimation", slug: "funimation", icon: "🎬", sortOrder: 233 },
  { name: "VRV", slug: "vrv", icon: "🎬", sortOrder: 234 },
  { name: "Tubi", slug: "tubi", icon: "🎬", sortOrder: 235 },
  { name: "Plex", slug: "plex", icon: "🎬", sortOrder: 236 },
  { name: "Kodi", slug: "kodi", icon: "🎬", sortOrder: 237 },
  { name: "VLC", slug: "vlc", icon: "🎬", sortOrder: 238 },
  { name: "PotPlayer", slug: "potplayer", icon: "🎬", sortOrder: 239 },
  { name: "MPC-HC", slug: "mpc-hc", icon: "🎬", sortOrder: 240 },
  { name: "KMPlayer", slug: "kmplayer", icon: "🎬", sortOrder: 241 },
  { name: "GOM Player", slug: "gom-player", icon: "🎬", sortOrder: 242 },
  { name: "SMPlayer", slug: "smplayer", icon: "🎬", sortOrder: 243 },
  { name: "Daum PotPlayer", slug: "daum-potplayer", icon: "🎬", sortOrder: 244 },
  { name: "5KPlayer", slug: "5kplayer", icon: "🎬", sortOrder: 245 },
  { name: "Elmedia Player", slug: "elmedia-player", icon: "🎬", sortOrder: 246 },
  { name: "IINA", slug: "iina", icon: "🎬", sortOrder: 247 },
  { name: "Movist", slug: "movist", icon: "🎬", sortOrder: 248 },
  { name: "MPlayerX", slug: "mplayerx", icon: "🎬", sortOrder: 249 },
  { name: "VLC for Mac", slug: "vlc-mac", icon: "🎬", sortOrder: 250 },
  { name: "QuickTime Player", slug: "quicktime", icon: "🎬", sortOrder: 251 },
  { name: "iTunes", slug: "itunes", icon: "🎵", sortOrder: 252 },
  { name: "Windows Media Player", slug: "wmp", icon: "🎬", sortOrder: 253 },
  { name: "Winamp", slug: "winamp", icon: "🎵", sortOrder: 254 },
  { name: "Foobar2000", slug: "foobar2000", icon: "🎵", sortOrder: 255 },
  { name: "AIMP", slug: "aimp", icon: "🎵", sortOrder: 256 },
  { name: "MusicBee", slug: "musicbee", icon: "🎵", sortOrder: 257 },
  { name: "Clementine", slug: "clementine", icon: "🎵", sortOrder: 258 },
  { name: "Rhythmbox", slug: "rhythmbox", icon: "🎵", sortOrder: 259 },
  { name: "Amarok", slug: "amarok", icon: "🎵", sortOrder: 260 },
  { name: "Banshee", slug: "banshee", icon: "🎵", sortOrder: 261 },
  { name: "Audacious", slug: "audacious", icon: "🎵", sortOrder: 262 },
  { name: "Deadbeef", slug: "deadbeef", icon: "🎵", sortOrder: 263 },
  { name: "Quod Libet", slug: "quod-libet", icon: "🎵", sortOrder: 264 },
  { name: "Exaile", slug: "exaile", icon: "🎵", sortOrder: 265 },
  { name: "Listen", slug: "listen", icon: "🎵", sortOrder: 266 },
  { name: "Strawberry", slug: "strawberry", icon: "🎵", sortOrder: 267 },
  { name: "Lollypop", slug: "lollypop", icon: "🎵", sortOrder: 268 },
  { name: "GNOME Music", slug: "gnome-music", icon: "🎵", sortOrder: 269 },
  { name: "Rhythmbox", slug: "rhythmbox-linux", icon: "🎵", sortOrder: 270 },
  { name: "Banshee", slug: "banshee-linux", icon: "🎵", sortOrder: 271 },
  { name: "Audacious", slug: "audacious-linux", icon: "🎵", sortOrder: 272 },
  { name: "Deadbeef", slug: "deadbeef-linux", icon: "🎵", sortOrder: 273 },
  { name: "Quod Libet", slug: "quod-libet-linux", icon: "🎵", sortOrder: 274 },
  { name: "Exaile", slug: "exaile-linux", icon: "🎵", sortOrder: 275 },
  { name: "Listen", slug: "listen-linux", icon: "🎵", sortOrder: 276 },
  { name: "Strawberry", slug: "strawberry-linux", icon: "🎵", sortOrder: 277 },
  { name: "Lollypop", slug: "lollypop-linux", icon: "🎵", sortOrder: 278 },
  { name: "GNOME Music", slug: "gnome-music-linux", icon: "🎵", sortOrder: 279 },
  { name: "VLC", slug: "vlc-linux", icon: "🎬", sortOrder: 280 },
  { name: "SMPlayer", slug: "smplayer-linux", icon: "🎬", sortOrder: 281 },
  { name: "MPV", slug: "mpv", icon: "🎬", sortOrder: 282 },
  { name: "Totem", slug: "totem", icon: "🎬", sortOrder: 283 },
  { name: "Parole", slug: "parole", icon: "🎬", sortOrder: 284 },
  { name: "Xine", slug: "xine", icon: "🎬", sortOrder: 285 },
  { name: "MPlayer", slug: "mplayer", icon: "🎬", sortOrder: 286 },
  { name: "FFmpeg", slug: "ffmpeg", icon: "🎬", sortOrder: 287 },
  { name: "HandBrake", slug: "handbrake", icon: "🎬", sortOrder: 288 },
  { name: "VLC", slug: "vlc-windows", icon: "🎬", sortOrder: 289 },
  { name: "PotPlayer", slug: "potplayer-windows", icon: "🎬", sortOrder: 290 },
  { name: "MPC-HC", slug: "mpc-hc-windows", icon: "🎬", sortOrder: 291 },
  { name: "KMPlayer", slug: "kmplayer-windows", icon: "Play", sortOrder: 292 },
  { name: "GOM Player", slug: "gom-player-windows", icon: "Play", sortOrder: 293 },
  { name: "SMPlayer", slug: "smplayer-windows", icon: "Play", sortOrder: 294 },
  { name: "Daum PotPlayer", slug: "daum-potplayer-windows", icon: "Play", sortOrder: 295 },
  { name: "5KPlayer", slug: "5kplayer-windows", icon: "Play", sortOrder: 296 },
  { name: "Elmedia Player", slug: "elmedia-player-windows", icon: "Play", sortOrder: 297 },
  { name: "IINA", slug: "iina-windows", icon: "Play", sortOrder: 298 },
  { name: "Movist", slug: "movist-windows", icon: "Play", sortOrder: 299 },
  { name: "MPlayerX", slug: "mplayerx-windows", icon: "Play", sortOrder: 300 },
  { name: "VLC for Mac", slug: "vlc-mac-app", icon: "Play", sortOrder: 301 },
  { name: "QuickTime Player", slug: "quicktime-mac", icon: "Play", sortOrder: 302 },
  { name: "iTunes", slug: "itunes-mac", icon: "Music", sortOrder: 303 },
  { name: "Windows Media Player", slug: "wmp-windows", icon: "Play", sortOrder: 304 },
  { name: "Winamp", slug: "winamp-windows", icon: "Music", sortOrder: 305 },
  { name: "Foobar2000", slug: "foobar2000-windows", icon: "Music", sortOrder: 306 },
];

export async function seed() {
  for (const cat of defaultCategories) {
    const existing = await db.select().from(categories).where(eq(categories.slug, cat.slug)).limit(1);
    if (existing.length === 0) {
      await db.insert(categories).values(cat);
    }
  }

  const adminExists = await db.select().from(users).where(eq(users.username, "admin")).limit(1);
  if (adminExists.length === 0) {
    const password = await bcrypt.hash("admin123", 10);
    await db.insert(users).values({
      username: "admin",
      password,
      isAdmin: true,
      isVerified: true,
      refCode: "ADMIN001",
    });
  }

  const testExists = await db.select().from(users).where(eq(users.username, "test")).limit(1);
  if (testExists.length === 0) {
    const password = await bcrypt.hash("test123", 10);
    await db.insert(users).values({
      username: "test",
      password,
      isAdmin: false,
      isVerified: true,
      refCode: "TEST001",
    });
  }

  console.log("Seed completed");
}
